### PR TITLE
Move distribution module hook to /x/

### PR DESCRIPTION
**Pull request by haasted**

### CODE REVIEW

**Comment by blewater** [comment]
Future suggestion, now that the `proxykeeper` has been simplified, another name closer to its mission would help identifying it.

**Comment by haasted** [comment]
I understand the comment in line 65 as a warning that we're using behaviour which is not strictly defined by the ABCI, but is rather implicit behaviour by Tendermint, so we should be aware of this we ever change out Tendermint for another consensus engine.

**Comment by haasted** [comment]
> This is a rather sophisticated module, Shouldn't there be unit tests 
> validating the module meets the SDK and/or e-money differentiation spec?

It is indeed. Fortunately the changes we've made are relatively benign, and incredible visible if they somehow do not work, ie. the chain will continously generate blocks as fast as possible due to constant state changes.

**Comment by haasted** [comment]
On second thought, I actually decided to leave the TODO in `abci.go` in order to retain the original structure of the file as much as possible.

**Review by blewater — APPROVED** [review]

**Pull request merged**
