### PR TITLE
Log buyback market order error

### PR DESCRIPTION
**Pull request by blewater**
Log buyback market order error instead of panic

### CODE REVIEW

**Review by haasted — APPROVED** [review]

**Comment by blewater** [comment]
@Mergifyio rebase

**Comment by blewater** [comment]
@Mergifyio refresh

**Comment by blewater** [comment]
@Mergifyio squash

**Comment by blewater** [comment]
@Mergifyio merge

**Comment by blewater** [comment]
@Mergifyio refresh

**Pull request merged**
